---
# Install Vector on Ubuntu (без GPG-ключа, с trusted=yes)

- name: Ensure prerequisites are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
    update_cache: true
  become: true
  tags: [install]

- name: Add Vector apt repo (trusted=yes, skip gpg check)
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/vector.list
    content: |
      deb [trusted=yes] https://packages.timber.io/vector/apt stable main
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: [install]

- name: Update apt cache after adding Vector repo
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: [install]

- name: Install Vector package
  ansible.builtin.apt:
    name: vector
    state: present
  become: true
  tags: [install]

- name: Ensure Vector service is enabled and started
  ansible.builtin.service:
    name: vector
    enabled: true
    state: started
  become: true
  tags: [install]
