---
- name: Ensure apt deps present
  ansible.builtin.apt:
    name: [ "apt-transport-https", "ca-certificates", "gnupg", "curl" ]
    state: present
    update_cache: true

- name: Add Vector GPG key
  ansible.builtin.apt_key:
    url: "{{ vector_repo_gpg_url }}"
    state: present

- name: Add Vector apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://repositories.timber.io/public/vector/deb/{{ vector_repo_distribution }} {{ vector_repo_codename }} main"
    filename: "vector"
    state: present

- name: Install vector
  ansible.builtin.apt:
    name: "{{ 'vector=' + vector_version if vector_version else 'vector' }}"
    state: present
    update_cache: true

- name: Ensure vector config directory exists
  ansible.builtin.file:
    path: "{{ vector_config_path | dirname }}"
    state: directory
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"
    mode: "0755"

- name: Deploy vector config
  ansible.builtin.template:
    src: "vector.yml.j2"
    dest: "{{ vector_config_path }}"
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"
    mode: "0644"
  notify: restart vector

- name: Ensure vector service enabled and started
  ansible.builtin.systemd:
    name: "{{ vector_service_name }}"
    state: started
    enabled: true